sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kHkRjuTS046ufh3lVf+HJAnuXD8qyYNEZ8d6qkBgcu8X3/GMdvohpGdr3A60QCFiM25YOqt3zAdTUAXA5MNpIsHBPBS53glroSJaOS0/9sjlLEdo7LK6G1RbY/WYj+x19V4bo6TfQCMxiXnskzYBYjfzBjS2WvN1IoFVVbXmRp3c9zRvTHWNqq98vYMhNdNK0DJtVvOGnTV9oGU+mE76CqKtuS6zxaH+lGu+xg4qngllqdt28wm7LTxzqfBuV3I5XhLgfIbDpko5OvOBCOBZzpy3gqYJTqtFq3QaOHIbe19NJlNtObjfEeCGLjuSW9+YybYpR64qL9ldcVvqWmiu+STtjvJWN8nrXxepUEt6Cac+yy7rEkWQLiuNv67ajoiZEy0/r1fwfHnpUgReZbB9vfaQylX02UXulVjSRoWxXf7LCCckh3ll3Y/90igeZtlSB6pRu1nh3LSOJeJn4Ybgnie4KRkk/HdFRd1G1iUdX4p9aWPm5cY2AYauJgdbm+l02Dz+2zU+2+4DOwBAtxWUnuo/aOuKTdORIoLRRlCQWKzReWzd2GhWC0zFCdx8ys2zH3uFYOx0xLuctRFw6q5I927rdAVEWesNd8KZwWO7K/18B3b/tW/BnWaRpIrZTsP6+sAq0uq0FrdcjznIVUZAqvK1kpjsSjwxpVrt42OdGsY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Essays-on-Russian-Novelists_5996
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy